import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import {NavBar} from "@/components/nav/nav-bar";
import "./globals.css";
import {authClient} from "@/lib/auth/client";
import {NeonAuthUIProvider} from "@neondatabase/auth/react";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <NeonAuthUIProvider
            authClient={authClient}
            redirectTo="/account/settings"
            emailOTP
            social={{
                providers: ['google']
            }}
        >
            <NavBar/>
            {children}
        </NeonAuthUIProvider>
        </body>
        </html>
    );
}
